# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/titanic',
                'doc_host': 'https://Kkhurana007.github.io',
                'git_url': 'https://github.com/Kkhurana007/titanic',
                'lib_path': 'titanic'},
  'syms': {'titanic.core': {'titanic.core.foo': ('core.html#foo', 'titanic/core.py')}}}
